version: '3.1'

services:
  rag-db:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: apirag